// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * @file   unittest_causallm_gemma4_reference.cpp
 * @date   15 June 2026
 * @brief  Differential (cross-validation) tests for the tiny Gemma4 model.
 *
 * Compares nntrainer's Gemma4 output against golden fixtures generated by
 * HuggingFace transformers (generate_gemma4_reference.py). The generic checks
 * live in causallm_test_utils; this file only binds the Gemma4 adapter and the
 * fixture name. Gemma4 sanitizes its configs in the Transformer constructor, so
 * a thin subclass supplies that constructor while inheriting all inference
 * methods from CausalLMTestAdapter. Tests skip automatically when fixtures or
 * the nntr_quantize binary are absent.
 *
 * @see    https://github.com/nntrainer/nntrainer
 * @author Jungwon Lee <jungone.lee@samsung.com>
 * @bug    No known bugs except for NYI items
 */

#include <causallm_test_utils.h>

#include <gtest/gtest.h>

#include <gemma4_causallm.h>

#include <memory>

namespace {

/**
 * @brief Gemma4 adapter that sanitizes configs before Transformer init
 */
class ReferenceGemma4 final
  : public causallm_test::CausalLMTestAdapter<causallm::Gemma4CausalLM> {
public:
  ReferenceGemma4(causallm::json &cfg, causallm::json &generation_cfg,
                  causallm::json &nntr_cfg) :
    causallm::Transformer(
      causallm::Gemma4Transformer::sanitizeConfig(cfg),
      causallm::Gemma4Transformer::sanitizeGenerationConfig(generation_cfg, cfg),
      nntr_cfg, causallm::ModelType::CAUSALLM),
    causallm_test::CausalLMTestAdapter<causallm::Gemma4CausalLM>(
      cfg, generation_cfg, nntr_cfg) {}
};

/**
 * @brief Differential model descriptor for the tiny Gemma4 fixture
 */
causallm_test::DifferentialModel gemma4Model() {
  return {
    "gemma4_tiny",
    [](causallm::json &cfg, causallm::json &gen_cfg, causallm::json &nntr_cfg) {
      return std::make_unique<ReferenceGemma4>(cfg, gen_cfg, nntr_cfg);
    },
  };
}

/**
 * @brief FP32 prefill logits and greedy tokens match the HF reference
 *
 * TODO: This test is currently failing. The maximum absolute logit difference
 * exceeds the 1e-2 tolerance (observed ~0.0114 at a single index). Root cause
 * has not been identified yet — suspected sources are Gemma4-specific ops
 * (per_layer_input mechanism, reshaped_rms_norm, or tanh-GELU approximation).
 * Investigate and fix before enabling.
 */
TEST(Gemma4DifferentialTest, FP32MatchesHFReference) {
  causallm_test::runFp32DifferentialChecks(gemma4Model());
}

/**
 * @brief Q4_0 quantized logits stay within tolerance of the FP32 reference
 */
TEST(Gemma4DifferentialTest, Q40CloseToFP32Reference) {
  causallm_test::runQ40DifferentialChecks(gemma4Model());
}

} // namespace
